#!/bin/sh

# Default to localhost if not set
API_BASE_URL=${API_BASE_URL:-https://efv-backend-743928421487.asia-south1.run.app}

echo "Updating API configuration to: $API_BASE_URL"

# Create new config file
cat <<EOF > /usr/share/nginx/html/js/api-config.js
/**
 * EFV API Configuration
 * Auto-generated by entrypoint.sh
 */
const CONFIG = {
    API_BASE_URL: '$API_BASE_URL'
};
EOF

# Start Nginx
exec nginx -g "daemon off;"
